name: CI
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          # Убираем cache: "npm" так как используем pnpm

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: TypeScript type check (backend only)
        run: pnpm --filter backend run type-check

      - name: Run linting (backend only)
        run: pnpm --filter backend run lint

      - name: Run tests (backend only)
        run: pnpm --filter backend run test

      - name: Build projects (backend only)
        run: pnpm --filter backend run build
